version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - shared-network
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./token.json:/app/token.json:ro
      - ./credentials.json:/app/credentials.json:ro

networks:
  shared-network:
    external: true